### ISSUE TITLE
Error in use full-sync

### ISSUE THREAD

**Issue by Erland366** [colabond/colabond-cli#1]
``` 
Traceback (most recent call last):
  File "/home/erland/.local/lib/python3.8/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/erland/.local/bin/colabond", line 8, in <module>
    sys.exit(main())
  File "/home/erland/.local/lib/python3.8/site-packages/colabond/colabond.py", line 432, in main
    full_sync()
  File "/home/erland/.local/lib/python3.8/site-packages/colabond/colabond.py", line 130, in wrapper
    return func(*args, **kwargs)
  File "/home/erland/.local/lib/python3.8/site-packages/colabond/colabond.py", line 151, in wrapper
    return func(*args, **kwargs)
  File "/home/erland/.local/lib/python3.8/site-packages/colabond/colabond.py", line 88, in wrapper
    return func(*args, **kwargs)
  File "/home/erland/.local/lib/python3.8/site-packages/colabond/colabond.py", line 384, in full_sync
    if r.json()["status"] == "error":
  File "/home/erland/.local/lib/python3.8/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
Error appear when using command `colabond full-sync`

**Comment by ariaghora** [comment]
Yep. It is a server issue (server is not live yet). Seems I won't fix it anytime soon. OTOH, I'm rewriting (and rebrand) the tool, but not sure when it's gonna be shipped, though. Thanks for trying, anyway.
